### ISSUE TITLE
makeVList fails immediately in sizing group

### ISSUE THREAD

**Issue by edemaine** [KaTeX/KaTeX#1788]
Dear `makeVList` experts: I'm encountering a bug where negative shifts do not work when they come just inside a sizing group (as made by `\large`, `\huge`, etc.).  Here is an example:

```latex
A\raisebox{-1ex}{B}
\large A\raisebox{-1ex}{B}
\huge A\raisebox{-1ex}{B}
\large {A\raisebox{-1ex}{B}}
\huge {A\raisebox{-1ex}{B}}
```

Rendering on katex.org (ignore wrong font size for B):

![image](https://user-images.githubusercontent.com/2218736/48875317-5038b000-edc6-11e8-9294-c663ad2165b7.png)

Rendering with #1787 applied (correct font size for B):

![image](https://user-images.githubusercontent.com/2218736/48875294-149de600-edc6-11e8-9f14-9514f79243c1.png)

The middle examples like `\large A\raisebox{-1ex}{B}` aren't descending the `B` at all.

Any ideas what's wrong?  Everything works fine for positive vertical ascents (positive `\raisebox`).

**Comment by ronkok** [comment]
I don't have a solution, but  I can point out part of the problem. Consider the rendering from `\large A\raisebox{-1ex}{B}`. The subscript is contained in a set of nested spans. The outer span has the CSS classes: `vlist-t vlist-t2 sizing reset-size6 size7`.

Classes `vlist-t vlist-t2` are put there by `makeVList`. `vlist-t` sets the display to `inline-table`.

Classes `sizing reset-size6 size7` are put there by `\large`. `sizing` overrules what `makeVList` did and sets the display to `inline-block`. 

The inner nested spans have `display: table-row;` and `display: table-span` but they don't work because they're not in an `inline-table`.

I don't know why a font change would need a `inline-block` rule. Maybe it could be omitted. Or maybe the `VList` could be nested inside the font change span instead of sharing the same span.

**Comment by ronkok** [comment]
Or maybe `vlist-t`  just needs to be pushed to the array of classes instead of unshifted?

**Comment by kevinbarabash** [comment]
The order that classes appear in the `class` attribute of an element don't impact the order their applied in unfortunately.  The thing that defines the order of application is the order that the classes appear in the CSS file.  This is why CSS classes is bad. :(
