### ISSUE TITLE
Colored bracket.

### ISSUE THREAD

**Issue by ro70** [KaTeX/KaTeX#1844]
LaTeX renders

$$\ln\left(x\color{red}\right)y$$

as expected. The closing bracket is red. It's the only character that is red.

With KaTeX there is no red bracket. How can I achieve this?

**Comment by edemaine** [comment]
@ro70 Thanks for the report! That is behavior I wasn't familiar with: `\right` ends the group that has the defined color, but the closing character is the last thing with the color.  I'll take a look at this...

A workaround for now would be to use `\big` and friends instead of `\left`/`\right`, as in:
```latex
\ln\big(x\textcolor{red}{\big)}y
```
which renders as

![image](https://user-images.githubusercontent.com/2218736/52438686-dcb25f00-2ae7-11e9-857a-bf23dfba09e6.png)

**Comment by ro70** [comment]
@kevinbarabash @edemaine Thank you!
