### ISSUE TITLE
Chrome on Linux MathML Code are disappear - with Node.JS

### ISSUE THREAD

**Issue by balakrishnan1978** [KaTeX/KaTeX#1957]
Dear all,
On our project uses KaTeX to display math. When using Node.JS(Server) with KaTeX all the MathML are disappear. (Only for Chrome Browser)

On the same method without Node.JS(Server) all the MathML are shown correct (Include Chrome, Opera, FireFox)
How to fix the problem in Chrome?

Thanks in advance.

**Comment by edemaine** [comment]
@balakrishnan1978 We'll need more details to help you debug. What you describe should work fine, except that MathML (currently) doesn't render in any case -- KaTeX uses HTML to render its math.  Can you send an example of the output you're getting from the server, for example?

**Comment by balakrishnan1978** [comment]
![Chrome_Local_Screenshot](https://user-images.githubusercontent.com/5443482/56877706-8fea7e80-6a6d-11e9-86c3-18faf1de093b.png)
![Chrome_Server_Screenshot](https://user-images.githubusercontent.com/5443482/56877707-8fea7e80-6a6d-11e9-9060-aecaf9458658.png)
@edemaine Thanks for your reply and please find attached the screenshot for your reference. You can see when i was viewing in Local MathML are appear and viewing in Server MathML are disappear. Could you please advise how to solve this issue...

**Comment by edemaine** [comment]
In regular KaTeX, the `.katex-mathml` element is hidden (size 1x1), so the local behavior you're seeing is actually the expected one.  KaTeX also doesn't use the `canvas` element, so some software other than KaTeX (perhaps [WeTeX](https://github.com/Sukii/WeTeX)?) is creating that.  In summary, this doesn't seem to be a KaTeX issue, but rather something else failing to activate.

There is a lot of the web that changes (because of security rules) when switching to local. I'd check your console and network logs to see if something is failing to load.

**Comment by balakrishnan1978** [comment]
![Screenshot from 2019-05-02 10-56-23](https://user-images.githubusercontent.com/5443482/57057797-19e25380-6cc9-11e9-80ba-93366f90d511.png)
Hi edemaine,
I have gone the solution. When i was removed unwanted `FMath` plugin in Chrome it's showing. Please find attached the screenshot for your reference.
