### ISSUE TITLE
Using watu2 quiz; katex does not render properly

### ISSUE THREAD

**Issue by autarkaw** [KaTeX/KaTeX#1974]
I am using katex wp plugin in wordpress site for Watu Quiz.  It renders equations nicely in the question statement but does a poor job of alignment in the multiple-choices.  See here for example.  https://numericalmethods.autarkaw.com/quiz-publish/ See how the a_b is all over the place.  I simply used [latex] a_b [/latex], the same I used in the question statement where it renders beautifully.

**Comment by ronkok** [comment]
@autarkaw It's a CSS problem. One of the CSS files is `'https://numericalmethods.autarkaw.com/wp-content/plugins/watu/style.css?ver=2.3.1'` and it contains the following rule:
```
.answer span {
	padding-right:20px;
}
```

That rule selects every span that is a descendant of class `answer` and applies 20px of right padding to each individual span. Instead of a `.answer span` selector, it should use a `.answer>span` selector. Then only the direct descendant would get that 20px padding and the more deeply nested KaTeX descendant spans would all be rendered properly.

**Comment by autarkaw** [comment]
Thank you - that did it - that was simple and most helpful.  Any suggestions on the latex not rendering when submit button is used and it shows the answers.

**Comment by edemaine** [comment]
KaTeX needs to be called to render the math. Probably the katex wp plugin isn't being called when Watu Quiz does its thing? You'd probably be best off asking in a Watu Quiz forum.
