### ISSUE TITLE
Inline SVG as img tags

### ISSUE THREAD

**Issue by mbarkhau** [KaTeX/KaTeX#1977]
I'm trying to have a nice way to render math with WeasyPrint. Unfortunately WeasyPrint doesn't support inline SVG images and from the timeline of Kozea/WeasyPrint#75 this may not change any time soon. As a stop-gap measure I'm postprocessing the output of KaTeX and have replaced the inline SVG tags with img tags and base64 encoded svg images.

Here is some example output: https://gist.github.com/mbarkhau/ff263164cd162ff1fd734c2b0ce23241

Unfortunately some of the rules of `katex.css` are not applied to the img tags. This is fine for such things as `stroke` and `fill` (I don't expect css rules to apply inside an SVG rendered as an img), but not for styles related to layout of the img itself. To fix this for the above example, I added the following styles, taken from the `.katex svg` rule in `katex.css`.

```css
    .katex img {
      display: block;
      position: absolute;
      width: 100%;
      height: inherit;
    }
```

My request would be to add the above rules (or equivalent) to `katex.css`. This would allow me to use the standard version of `katex.css` for my post-processed output.

I hope such a change won't break any existing rendering (are img elements used for other things inside of `<span class="katex">` ?). If it would break things, then I could for example add `class="svg"` to the img tag during the post-processing, which would allow for a more specific rule that wouldn't interfere with the rendering of other img elements.

In the particular example I chose the inline SVG tags did not appear to depend on the CSS rules, which made this approach possible. Judging by the use of `stroke` and `fill` in `katex.css`, I imagine this isn't true in general. Are the square root symbols an overly simplified case and there are other cases for which this post-processing approach would break?

**Comment by ronkok** [comment]
@mbarkhau That's an interesting problem and you are taking an interesting approach. 

Where are you getting the base64 encoded svg images? Are they static SVGs from the paths in KaTeX `svgGeometry.js`? If so, you should know that KaTeX now modifies the height of very tall `\sqrt` radicals at runtime, and if PR #1964 is approved, then many more radicals would be modified at runtime.

I can't think of any reason otherwise why your proposal would not work, but I want to give it more thought before I'm sure.

**Comment by mbarkhau** [comment]
[The output](https://gist.github.com/mbarkhau/ff263164cd162ff1fd734c2b0ce23241) was generated using the [markdown-katex package](https://pypi.org/project/markdown-katex/). Yes KaTeX is bundled together with 3 node interpreters in a python package; I hope the gods will forgive me.

More specifically, the html output generated by `katex-cli` is post-processed using [`svg2img(html: str) -> str:`](https://gitlab.com/mbarkhau/markdown-katex/blob/master/src/markdown_katex/extension.py#L45).

It "parses" the html using the regexp `<svg.*?</svg>` and replaces every match with a reencoded `<img src="
data:image/svg+xml;base64,...">` equivalent. In other words, this assumes the output of katex-cli is final and can be rendered statically. I'm not sure if the height modifications at runtime that you mentioned are precluded by that.

**Comment by ronkok** [comment]
@mbarkhau A post processor as you describe will work fine. The runtime height is already set before your post-processor begins work.

As to your original question, will KaTeX adopt a `.katex img` selector and rule? On that question I will defer to @kevinbarabash. You might try putting  your code into  `katex.less` and opening a pull request.

**Comment by edemaine** [comment]
@ronkok How would the proposed `.katex img` rule interact with your forthcoming support of `\includegraphics`?

I find the rule pretty weird, so my feeling is that it doesn't seem like a good general thing to include. But I'm happy to be convinced otherwise if you can explain the rule.

I also don't understand the motivation for pushing these changes into KaTeX directly. Why can't you have a second CSS file?

**Comment by mbarkhau** [comment]
> I also don't understand the motivation for pushing these changes into KaTeX directly. Why can't you have a second CSS file?

I think it was a bad idea. You're right, I'll just add a custom rule as part of the page.
