### ISSUE TITLE
Line breaks within \text for inline formulas

### ISSUE THREAD

**Issue by ccreus** [KaTeX/KaTeX#1992]
The title says it all: allow line breaks at the spaces within a `\text` block when rendering inline formulas. That might be useful for expressions like `$\{x \in S \mid x\text{ some very wordy property} \}$`.

As far as I know, that would not be the standard behavior of `\text` in LaTeX, so I understand that this feature might be unfit for KaTeX (unless it is behind some disabled-by-default option). Also, simple workarounds do exist, like manually breaking the formula to leave the contents of `\text` outside the formula, so that KaTeX does not handle that part.

**Comment by edemaine** [comment]
@ccreus I don't see how this is reasonable, because it deviates from LaTeX behavior. I just confirmed that `$\text{long text \allowbreak long text \allowbreak ...}$` doesn't allow for any linebreaks. It's simply not how TeX works.  You can use $\text{long text} \allowbreak \text{long text} \allowbreak ...}$ and line breaks will be possible, both in LaTeX and KaTeX.  (In case you didn't know: KaTeX supports automatic line breaking in inline math, in the same way TeX does: it will break after an operator or binary or an `\allowbreak`.)

**Comment by ccreus** [comment]
Indeed, as I said, I was aware that it is not standard LaTeX behavior and that it might be better as a disabled-by-default option.  I still find it reasonable, though, as with LaTeX the paper dimensions are fixed at compile time and the manual tweaking of formulas is rather limited (i.e., put the `\allowbreak` at the exact spots where they are needed), whereas with KaTeX the dimensions of the screen are not necessarily known beforehand and the tweaking needs more guesses (e.g., changing each space in the original `\text{...}` into ` } \allowbreak \text{` or simply change the whole `\text{...}` into `$ ... $` to cut the formula and leave the long text outside; or reformulate and avoid the long text altogether).

Well, we may agree to disagree. I'll keep using the LaTeX workarounds.

PS: I also knew that KaTeX supports automatic line breaking: it is one of the key features that made me update to 0.10.0-beta back in the day. Can't wait to have #1233 and #1546 fixed.
