### ISSUE TITLE
How should I use mhchem in vue?

### ISSUE THREAD

**Issue by doraven** [KaTeX/KaTeX#1995]
I have tried a lot of methods to get mhchem run. Not working.

Math equations are working fine.
![Math eq works fine](https://user-images.githubusercontent.com/15844287/58973725-3ce5b300-87f3-11e9-9807-317d41867a07.png)

Here is my code:

> I use a .js file to import katex

```javascript
import katex from 'katex'
import "katex/dist/katex.min.css"
import 'katex/dist/contrib/mhchem'
```

This is not working properly as I render as following

```javascript
let tex = data[i].data.trim()
if(tex.indexOf("\\ce{") === -1 )
    washedData.push(katex.renderToString(tex, {displayMode: false}))
else
    washedData.push(katex.renderToString(tex.slice(4, -1), {displayMode: false}))
```
![Pictures of rendered: not using mhchem](https://user-images.githubusercontent.com/15844287/58973749-4d962900-87f3-11e9-9d4e-d9e48dd5eac1.png)

>I tried to remove `\ce`, not working.ERORR:
>
>>KaTeX parse error: Undefined control sequence: \ce at position 1: \̲c̲e̲{x Na(NH4)HPO4 …

My problem is , how do we import mhchem when using webpack, such as vue which I am using now.

**Comment by doraven** [comment]
PS: I tried with include CDN in my index.html file, also failed.

**Comment by edemaine** [comment]
The first code block seems reasonable: you import `mhchem` immediately after importing `katex`.

The second code block should not remove the `\ce{...}` wrapper -- you need that wrapper.  The very first thing that `mhchem` does is define ` \ce` macro in the `katex` module; see [the source](https://github.com/KaTeX/KaTeX/blob/master/contrib/mhchem/mhchem.js).

Can you include a complete example of HTML + JS, maybe as a gist or existing github repo?

**Comment by doraven** [comment]
> 
> Can you include a complete example of HTML + JS, maybe as a gist or existing github repo?
>

I created a minimal-vue to test for mhchem. 

![minimal-vue](https://github.com/doraven/minimal-vue)

It's still not working with error:

```
ParseError: KaTeX parse error: Undefined control sequence: \ce at position 1: \̲c̲e̲{x Na(NH4)HPO4 …
```

**Comment by doraven** [comment]
I tried building with CDN libraries in vuejs.

It works.

![图片](https://user-images.githubusercontent.com/15844287/59017053-3b5ccf00-8875-11e9-85e2-9d077a79e936.png)

> That means, it doesn't work with development env of vue. But using CDN libraries is fine.

**Comment by edemaine** [comment]
Thank you for the complete example! This is very helpful.

**Fix:** replace `import 'katex/dist/contrib/mhchem'` with `import 'katex/dist/contrib/mhchem.js'` and everything seems to work.

**How I got there:**
I've found something that may be causing the problem: the built app code compiles `import katex from 'katex'` into
```js
var katex__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! katex */ \"./node_modules/katex/dist/katex.js\");
```
whereas the built `mhchem.js` code compiles `import katex from "katex"` into
```js
var _katex_mjs__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ../katex.mjs */ \"./node_modules/katex/dist/katex.mjs\");
```
Ah, the issue seems to be that `import 'katex/dist/contrib/mhchem'` ends up including `"./node_modules/katex/dist/contrib/mhchem.mjs"` instead of `.js`, which in turn imports `katex.mjs` instead of `katex.js`.

I'm not sure whether this suggests any changes on the KaTeX side.  I believe we currently don't expose `katex.mjs` via `package.json`, but perhaps now is the time to do so, if Webpack gets confused in this way?

**Comment by doraven** [comment]
## Thank You Very Much !!!
@edemaine 

Well, for me, the problem is solved. 

- If someone happens to go the same way I went through, he can find the solution here. 

- Update the document, either inside mhchem source code or in mainpage of mhchem would help a lot.

More professional thoughts or changes is far out of my ability.

Thank you again. If there is something I can do for katex, please let me know.
