### ISSUE TITLE
`\pmb` inside `\frac` renders double when not in display mode

### ISSUE THREAD

**Issue by lishid** [KaTeX/KaTeX#2001]
**Describe the bug:**
Go to https://katex.org/
Turn off displayMode and paste test code below

**(La)TeX code:**
```latex
\frac{\pmb{a}}{\pmb{c}}
```

**Expected behavior:**
No double rendering of characters

**Screenshots:**
![image](https://user-images.githubusercontent.com/609710/59314457-7d29b300-8c83-11e9-8552-909707aab1d4.png)

**Environment (please complete the following information):**
 - KaTeX Version: v0.10.2
 - Device: Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version: 74

**Comment by ronkok** [comment]
@lishid Thank you for the note, because you are right, that is a bug in the current KaTeX, release 10.2.

You'll find that this is resolved in the next release. PR #1924, already merged into master, fixes this problem. As evidence, I offer the following screenshot of a fraction in displaystyle and textstyle.

![pmb](https://user-images.githubusercontent.com/16403058/59394418-77d87100-8d34-11e9-8bb9-5e9fb3e497ea.PNG)

**Comment by lishid** [comment]
Alright, thanks for this information!
