### ISSUE TITLE
Digamma support

### ISSUE THREAD

**Issue by balakrishnan1978** [KaTeX/KaTeX#2002]
I have the below LaTeX Code
```\begin{array}{l}\textrm{𝟊𝟋}\end{array}```
The Error is showing
**Font metrics not found for font: .**
How to resolve this problem.

KaTeX Version   : 0.10.2
Device          : Desktop
OS              : Ubuntu Version 16.04
Browser         : Chrome
Version         : 75.0.3770.80

**Comment by edemaine** [comment]
@balakrishnan1978 If you're happy with the rendering, you can safely ignore the font metrics warning.

KaTeX supports `\digamma` (from `amssymb` package) that looks like ![image](https://user-images.githubusercontent.com/2218736/59436220-3049f780-8dbd-11e9-92a4-a00a0c3bffc8.png). @ronkok Should we add Unicode support for this?

It seems that LaTeX does not have support for lower-case digamma. This will make it difficult to support directly in KaTeX.

**Comment by balakrishnan1978** [comment]
@edemaine: KaTeX is support \digamma is working fine. But it will not support direct 𝟋 symbol?

**Comment by edemaine** [comment]
@balakrishnan1978 I meant "don't pay attention to the warning". It currently can't be turned off; this is issue #1950.

You're right that direct Unicode input of digamma isn't currently supported, but that would be easy to add. Hopefully @ronkok, who has been our expert on these sorts of decisions, can weigh in, and then we can add it to the next release. For now, you can pass in an option of `{macros: {"\u03dd": "\\digamma"}}` and that should add the mapping you want.

**Comment by kevinbarabash** [comment]
Submitting a PR to add `{macros: {"\u03dd": "\\digamma"}}` would also be welcome.

**Comment by edemaine** [comment]
@kevinbarabash Actually, this can be achieved by passing in a final`true` argument to the symbol definition. Just need to check that it's consistent witg xelatex etc.

**Comment by ronkok** [comment]
Well, here's some belated information about `\digamma`. It's a thoroughly confused situation, which is why we've avoided Unicode support so far. In tabular form:

| Code Point   | U+03DC     | U+03DD  |   U+1D7CA   | U+1D7CB   |
| ------------ | ---------- | --------- | --------- | --------- |
| Unicode Description | Greek Letter Digamma  | Greek Small Letter Digamma  | Mathematical Bold Capital Digamma  | Mathematical Bold Small Digamma |
| Example      | Ϝ          |  ϝ  |  𝟊  |  𝟋  |
| AWS          | \digamma   |     |     |     |
| stix           | \digamma   |     |     |     |
| KaTeX        | \digamma   |     |     |     |
| teubner      | \Digamma	  | \digamma   |             |             |
| boisik        | \Digamma	  | \digamma   |             |             |
| MathJax     | \Digamma	  | \digamma   |             |             |
| unicode-math | \upDigamma | \updigamma | \mbfDigamma | \mbfdigamma |


AWS got things off on the wrong foot with their choice of function name. In TeX, capital letters are usually called by a capitalized function name. But even though Ϝ is a capital letter, AWS used a non-capitalized function name to call it.

MathJax, teubner, and boisik  disagree with that decision. unicode-math differs from all of them and makes up its own function names. So there really isn't any standard way to map these Unicode characters to a function name.

The OP's example, by the way, shows the bold letters. The KaTeX fonts don't have glyphs for those code points, or for the small letter digamma, ϝ.

Given the KaTeX fonts that we have, I'd say we could insert a "true" into the `\digamma` line of `symbols.js`. That would add solid support for the capital, non-bold, letter Ϝ. The other letters are supported like any other unusual Unicode letters, with a glyph from a system font and a console error message. That's about as good as we can do short of a font upgrade.

**Comment by ronkok** [comment]
My previous comment on `\digamma` was incorrect and I've done a major edit. If you are reading the email version of this, it's better on the GitHub page.

**Comment by kevinbarabash** [comment]
> Given the KaTeX fonts that we have, I'd say we could insert a "true" into the \digamma line of symbols.js. That would add solid support for the capital small, non-bold, letter digamma. The other letters are supported like any other unusual Unicode letters, with a glyph from a system font and a console error message. That's about as good as we can do short of a font upgrade.

Sounds good.  Thanks for checking different packages to see what codepoint they map `\diagamma` to.  I'm glad that they're consistent.
