### ISSUE TITLE
Katex auto-render issue 

### ISSUE THREAD

**Issue by Color87CEEB** [KaTeX/KaTeX#2006]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
When using [`markor` an android text editor](https://github.com/gsantner/markor) to render Katex functions, some of them requires double backslashes to render properly. The developer believes this is the auto-render (`auto-render.min.js`) issue. 

**Screenshots:**
![Screenshot_20190629-193213-01](https://user-images.githubusercontent.com/37738001/60388114-7a321d80-9adf-11e9-8c4e-0e96df1434f1.jpeg)
![Screenshot_20190629-193222-01](https://user-images.githubusercontent.com/37738001/60388115-7a321d80-9adf-11e9-85ac-a6088590c5bc.jpeg)

**Comment by edemaine** [comment]
The Markdown renderer of Markor must be activating before KaTeX, which is removing backslashes from your text (because `\\` in Markdown renders as `\`).  This isn't KaTeX's fault; it's the Markdown renderer's.  The usual solution is to modify the Markdown renderer to parse math expressions (like `$...$` and `$$...$$`) and either call KaTeX's `renderToString` and render immediately (no auto-render required, which is ideal), or at least not mess with the enclosed string so that auto-render can then do its job.  Hope this helps!
