### ISSUE TITLE
\fbox does not support superscript, subscript

### ISSUE THREAD

**Issue by mpolyak** [KaTeX/KaTeX#2078]
As part of an effort to upgrade KaTeX from version 0.9 to the current version 0.11 on www.khanacademy.org we ran an audit of published math content on the site, to compare parse errors using KaTeX 0.11 vs the (currently used) KaTeX 0.9 library version.

We found that that expressions using \fbox with superscript, subscript fail to parse with KaTeX 0.11:

superscript
```
\fbox{V^a}

ParseError: KaTeX parse error: Expected '}', got '^' at position 8: \fbox{V^̲a}
```

subscript
```
\fbox{V_a}

ParseError: KaTeX parse error: Expected '}', got '_' at position 8: \fbox{V_̲a}
```

Interestingly, `\boxed` does support superscript, subscript. The following parses successfully:
```
\boxed{V^a} \boxed{V_a}
```

**Comment by edemaine** [comment]
This is in fact correct LaTeX behavior: `\fbox`'s argument is interpreted in text mode, while `\boxed`'s argument is interpreted in math mode.  You could restore the old behavior by defining a macro like `'\\fbox': '`\\boxed`'`, but it would be better to fix the original content to used `\boxed` instead of `\fbox` (or to use `\fbox{$...$}`).

**Comment by mpolyak** [comment]
Thank you @edemaine! I'll file this as an issue with our content team.

**Comment by kevinbarabash** [comment]
This is a case where we could probably improve our error messages.  When we detect characters that aren't allowed in `text` mode we could say `'^' not allowed in text mode` or something like that.
