### ISSUE TITLE
Not rending latex modifiers

### ISSUE THREAD

**Issue by tbhaxor** [KaTeX/KaTeX#2087]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [ ] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
There is rendering issue when using katex and latex modifiers

**(La)TeX code:**
The code of (La)TeX you tried to render:
```latex
${\displaystyle |\psi \rangle =\alpha |0\rangle +\beta |1\rangle }$
```

**Expected behavior:**

![](https://latex.codecogs.com/gif.latex?${\displaystyle%20|\psi%20\rangle%20=\alpha%20|0\rangle%20+\beta%20|1\rangle%20}$)

_from: latex.codecogs.com_

**Screenshots:**

![image](https://user-images.githubusercontent.com/28386721/63653380-8954e500-c789-11e9-8dce-5e9ff58d3f40.png)

`le` of displaystyle is rendered :man_facepalming: 

**Environment (please complete the following information):**
 - KaTeX Version: ^0.10.1 with `showdown-katex`
 - Device: Desktop
 - OS: Arch Linux
 - Browser: Any
 - Version: Any

**Comment by ronkok** [comment]
`showdown-katex` can render either KaTeX or [AsciiMath](http://asciimath.org).  I can reproduce the faulty rendering on the `showdown-katex` [demo page](https://obedm503.github.io/showdown-katex/) by submitting the string to an AsciiMath field instead of to a KaTeX field. 

![showdown](https://user-images.githubusercontent.com/16403058/63656861-96081780-c74e-11e9-99dd-5a51db3d3edc.PNG)

The same imput string, when submitted to a KaTeX field on the demo page, renders correctly.

I would speculate that your installation is set so that the `$...$` delimiters are programmed to invoke AsciiMath instead of KaTeX.

**Comment by tbhaxor** [comment]
So how do i fix it 
the showdown-katex is using 0.10 version of katex

**Comment by edemaine** [comment]
As @ronkok wrote above, the fix is likely to change the configuration in showdown-katex to use LaTeX mode instead of ASCII math mode. If it's not clear from the documentation, perhaps you should open an issue for showdown-katex. We know KaTeX but unfortunately not as much about showdown-katex.

**Comment by tbhaxor** [comment]
@ronkok 
```js
    {
      displayMode: true,
      throwOnError: false, // allows katex to fail silently
      errorColor: '#ff0000',
      delimiters: [
        { left: "$", right: "$", display: false }, // katex default
        { left: '~', right: '~', display: false, asciimath: true },
      ],
    }
```

This is my configuration

**Comment by ronkok** [comment]
@tbhaxor You need to raise this issue in a `showdown-katex` forum, not here. We don't know `showdown-katex` here and we can't tell if such a configuration is well formed or not.

If you get to the point where you have successfully invoked KaTeX and not AsciiMath, and then KaTeX is still acting improperly, then please come back and raise a new KaTeX issue here.
