### ISSUE TITLE
\cal support

### ISSUE THREAD

**Issue by edemaine** [KaTeX/KaTeX#2115]
KaTeX supports the new-style `\mathcal{...}` but not the old-style `{\cal ...}` font format.  We should ideally support both, as we do for `\rm`/`\mathrm` etc.; see the [support table](https://katex.org/docs/supported.html#style-color-size-and-font).

This oversight was recently mentioned to me by the author of a project using KaTeX as a common issue with KaTeX where they needed to fall back to MathJax, so I think it's relevant to the real world.

**Comment by nisha2107** [comment]
Hi @edemaine, 

I see from above comments that this issue is marked as fixed with your enhancement in code, But after i implemented Katex with my Angular project I see the error for '\cal'. 
![image](https://user-images.githubusercontent.com/17924176/99935624-05c6e100-2d9c-11eb-983a-ffac1d59f013.png)

the raw innerHTML: 
<p><span class="math-tex">\(f: {\cal R}^d\rightarrow {\cal R}\)</span></p>


I'm totally new to this library everything else is working as expected. 

For appreciation I must write that the library is really fast and my users are very happy.

**Comment by edemaine** [comment]
Sounds like you have an old version of KaTeX. Can you upgrade? You may be able to detect the version by entering `katex.version` in your JavaScript console.

**Comment by nisha2107** [comment]
Hi, @edemaine 

Thanks for your prompt response. 
My current version of katex is 0.11.1. May I know what is the latest stable version of katex library? and how can to upgrade in angular i am using yarn to install packages.

**Comment by nisha2107** [comment]
Hi @edemaine ,

Any update for my issue. I am still struggling to fix the above issue. 

Thanks

**Comment by edemaine** [comment]
@nisha2107 Probably you need to update to version 0.12.0, the latest. (https://katex.org/docs/ shows you the available versions in the top left.)

In your image above, you actually use a mix of 0.11.0 and 0.12.0, not 0.11.1... You shouldn't mix CSS and JavaScript across versions; ensure that they're all the same.

**Comment by nisha2107** [comment]
Hi @edemaine , 

Very thanks for your response. 
Finally I am able to resolve this by replacing '**\cal\** to '**\mathcal**'. It works absolutely perfect now. 

Once again thanks and have a great weekend.
