### ISSUE TITLE
How to get render complete event in Katex?

### ISSUE THREAD

**Issue by shah-xad** [KaTeX/KaTeX#2253]
I worked with MathJax, there we I get an event on a render complete like this.

```JavaScript
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, "myDiv"], function () {
        var height = document.getElementById('myDiv').clientHeight
    });
```

But I couldn't find anything related to this in Katex. I wanna calculate the height of div after render complete but it's calculating the div height before the render completes.

```JavaScript
        var myDiv = document.getElementById('myDiv');
        renderMathInElement(myDiv);
        var height = document.getElementById('teXHTML').clientHeight;
```

**Comment by mbourne** [comment]
I believe that's because your script is not waiting for the render step before going on immediately to find the height value. You could possibly get the height first, then set up a timer to wait until the height changes (as it almost always will) and capture that. However, that doesn't necessarily capture the whole event.

The approach I used on this comparison page was to wait for the "fonts loaded" event, assuming that was the last meaningful part of the math expression that the user needs to see.

https://www.intmath.com/cg5/katex-mathjax-comparison.php

It may or may not work for your situation.

**Comment by shah-xad** [comment]
@mbourne thanks I did a simple trick as you mentioned.

```
        renderMathInElement(myDiv);
        setTimeout(() => {
        var height = document.getElementById('teXHTML').clientHeight;
       .....
       .....
        }, 0)
```
Time is zero milliseconds :rofl: , but it worked like a charm.

**Comment by kevinbarabash** [comment]
Even though KaTeX renders things synchronously, the browser itself updates things asynchronous which is why the `setTimeout(..., 0)` is necessary.
