### ISSUE TITLE
Support arccot

### ISSUE THREAD

**Issue by Jshen6** [KaTeX/KaTeX#2274]
My code is "\arccot" and this wrong is "ParseError: KaTeX parse error: Undefined control sequence: \arccot at position 1: \̲a̲r̲c̲c̲o̲t̲ ̲x\sim-\frac1{1+…".
Why KaTex don't support arccot?

**Comment by edemaine** [comment]
KaTeX doesn't support `\arccot` because, as far as I can tell, LaTeX doesn't support `\arccot`.  I've never seen `arccot` (or `arcsec` or `arccsc`) arise naturally, though I imagine it could... On the other hand, if you can find a package in LaTeX that adds `\arccot` support, we could add support for it.

You can define your own support for `\arccot` by adding a `macros` option of
```
{'\\arccot': '\\operatorname{arccot}'}
```
or using `\def`/`\newcommand` within math itself.

**Comment by edemaine** [comment]
Closing for now. Let us know if you need more help defining a macro, or if you find a LaTeX package that supports `\arccot`.

**Comment by zyjdmmm** [comment]
https://github.com/microsoft/vscode/issues/218244
it's so strang in mardown of vscode,vscode use katex.but I use the typora is good work in $arccot x$.em....

**Comment by zyjdmmm** [comment]
i have a new discovery:
```
$\operatorname{arccot} x$//it runs
```
