### ISSUE TITLE
Font metrics not found for font

### ISSUE THREAD

**Issue by ratala1** [KaTeX/KaTeX#2281]
<img width="823" alt="Screen Shot 2020-06-29 at 10 49 55 AM" src="https://user-images.githubusercontent.com/11667120/85983556-514fab80-ba05-11ea-923d-5bb68a75c53d.png">

**Comment by ronkok** [comment]
KaTeX is designed to provide the benefits of LaTeX's math mode.  KaTeX is not a all-purpose text editor. It certainly is not an HTML parser. Your example is not well-formed LaTeX. 

Some editing environments support KaTeX between math delimiters, perhaps `$…$`. Then a person could write your example as:

> if $α, β$ are the zeros of polynomial $2y^2 + 7 + 5$, write the value of $(α + β)+α β$

KaTex would render the math between the `$…$` delimiters. What happens outside the delimiters is not KaTeX.

**Comment by MatiasLGonzalez** [comment]
Not totally related but I got this same issue viewing a Jupyter Notebook on VS Code, and found what was causing the issue was having the 𝛼 symbol directly, replacing it with the corresponding `\alpha` and `\beta` solved the problem

**Comment by edemaine** [comment]
@MatiasLGonzalez If you're having trouble rendering α, β directly, please open a new issue, and paste the actual α, β symbols you're using.

**Comment by MatiasLGonzalez** [comment]
Sure, but the issue seems to be related to the character been in [itallic](https://graphemica.com/%F0%9D%9B%BC) (U+1D6FC) (just like op),

![imagen](https://user-images.githubusercontent.com/48534497/131266648-a5c40583-f3dc-4b55-9477-5fb709d43682.png)

whereas if the character is in its "[normal](https://graphemica.com/%CE%B1)" (U+03B1) form it renders fine

![imagen](https://user-images.githubusercontent.com/48534497/131266681-5d39c71c-e6b0-43f5-9e35-46b11f9715fa.png)

I can open the issue if this is something that concerns KaTeX

**Comment by edemaine** [comment]
@MatiasLGonzalez Yes, please open a new issue. In addition to screen shots, please include the actual characters in your post (as text).

**Comment by MatiasLGonzalez** [comment]
@edemaine Issue is now open as #3212
