### ISSUE TITLE
Add umlauts to Fonts

### ISSUE THREAD

**Issue by StephanHoyer** [KaTeX/KaTeX#2587]
**Is your feature request related to a problem? Please describe.**
I want to use the very nice Roman font not only for formulas, but also for other parts of the page. But unfortunately Umlauts where not rendered as expected.

**Describe the solution you'd like:**
I want to use the font as normal web-font, but with umlauts rendered correctly.

**Describe alternatives you've considered:**
I tried to use the combined diaeresis, but without any luck

https://www.compart.com/en/unicode/U+0308

**Additional context:**
Umlauts working fine in katex-context, since the umlauts are built from two parts, the letter and the diaeresis. That however does not work for normal text.

As I see this, the umlauts are simply not embedded into the font. If they where, this would work fine, I think.

<img width="714" alt="Screenshot 2020-10-13 at 17 03 21" src="https://user-images.githubusercontent.com/54701/95878908-08ceba80-0d76-11eb-96c3-070c4586fbb3.png">

**Comment by edemaine** [comment]
This should probably be moved to the https://github.com/KaTeX/katex-fonts repository, as it's not related to KaTeX.

You're welcome to submit a PR that does this, but it would have to not break KaTeX. I recall we moved from combining accent characters to noncombining because of rendering issues with some web browsers (Safari). I think it would be possible to include both though...

**Comment by StephanHoyer** [comment]
moved to https://github.com/KaTeX/katex-fonts/issues/83
