### ISSUE TITLE
Unicode Character “𝜋” causes render error

### ISSUE THREAD

**Issue by dobesv** [KaTeX/KaTeX#2666]
**Describe the bug:**

We have users occasionally pasting the "unicode pi character" in for pi, which causes KaTeX to error out, even with strict mode off.

```latex
\text{𝜋}
```

Character: https://www.compart.com/en/unicode/U+1D70B

https://katex.org/?data=%7B%22displayMode%22%3Afalse%2C%22leqno%22%3Afalse%2C%22fleqn%22%3Afalse%2C%22throwOnError%22%3Afalse%2C%22errorColor%22%3A%22%23cc0000%22%2C%22strict%22%3A%22ignore%22%2C%22output%22%3A%22htmlAndMathml%22%2C%22trust%22%3Afalse%2C%22macros%22%3A%7B%22%5C%5Cf%22%3A%22%231f(%232)%22%7D%2C%22code%22%3A%22%5C%5Ctext%7B%F0%9D%9C%8B%7D%5Cnxxxxx%22%7D

![image](https://user-images.githubusercontent.com/327833/100686952-3971b000-3334-11eb-9cc9-b602ddbf9e47.png)

Since https://github.com/KaTeX/KaTeX/pull/1217 was merged it seemed like I should be able to use "any" Unicode character, but maybe I misunderstand.

**Expected behavior:**

I was hoping that by disabling strict mode it would at least not report an error - maybe skip that character or try to render it using the browser default font.

**Environment (please complete the following information):**

KaTeX Version: `0.12.0`

**Comment by dobesv** [comment]
It looks like there are a lot of characters in this block that maybe could be mapped to some corresponding ones that are supported by KaTeX: https://www.compart.com/en/unicode/block/U+1D400

I wonder if there's any automated way to do that.

**Comment by mbourne** [comment]
You can copy-paste ordinary pi (π), but not italic pi (𝜋).

![image](https://user-images.githubusercontent.com/7541940/100690828-53f26a80-33c2-11eb-84eb-2be1006c9b37.png)

Since pi should normally only ever be non-italic, seems that KaTeX is behaving appropriately. I found some of the characters in that U+1D400 block worked OK (like 𝑣), and others didn't (like 𝓀).

Is this happening with a lot of other characters, or just italic pi? Perhaps you could do a pre-process step and replace the italic pi with ordinary pi, as the user pastes into your application?

**Comment by dobesv** [comment]
Yeah, our current workaround is to add characters that people are having problems with into a static list.  It would be nice to find some already made mapping of italic & bold unicode mathematical characters back to the regular ones, though.

**Comment by dobesv** [comment]
It does also happen with omega & delta

**Comment by dobesv** [comment]
Anyway, maybe out of scope for KaTeX.  I hadn't noticed initially that these were the italic variants.
