### ISSUE TITLE
In chrome, when the font is less than 12px, the formula rendering is incorrect

### ISSUE THREAD

**Issue by lesonli** [KaTeX/KaTeX#2878]
latex : $m_1>m_2$

set ` <span class="katex" style="font-size: 12px;">`

The effect is as follows
![image](https://user-images.githubusercontent.com/17868761/113512432-2ea38200-9597-11eb-817b-ed3211a82bf3.png)

how to render correctly？
![image](https://user-images.githubusercontent.com/17868761/113512496-775b3b00-9597-11eb-9306-5cd7058aef49.png)

**Comment by edemaine** [comment]
It's hard to tell what you mean without a full example, but you presumably want to wrap the *entire* KaTeX output in `<span style="font-size: 12px;">...</span>`.  Don't modify the style of the existing `<span class="katex">`.

**Comment by Artoria2e5** [comment]
Problem repro'ed via https://jsbin.com/rasugel. Mininum text size setting in the browser is to blame: if you turn it all the way down, it scales perfectly.

I too initially thought it's related to the `font-style` setting conflicting with the CSS `.katex { font: ... }` directive, but it turns out to be not the case since the size of every child element is also defined relatively using `em`. Applying the size setting on it instead of a surrounding element does exacerbate it by skipping the `1.2em` magnification.

**Comment by edemaine** [comment]
I didn't realize that browsers had a minimum font size. 
 https://www.fyianlai.com/2012/01/google-chrome-minimum-font-size-issue/ suggests that the following CSS might fix your problem:
```css
html,
body {
    -webkit-text-size-adjust: none;
}
```

**Comment by lesonli** [comment]
Thank you for your reply
At present, chrome has disabled “text-size-adjust”, as long as the font-size is involved, we can not bypass this problem
I looked at the code of mathjax. They used CSS pseudo-class, before and after, to avoid this problem. Do we have any plans to implement rendering?

**Comment by Artoria2e5** [comment]
I feel that rendering character-by-character via CSS is directly against KaTeX's... philosophy(?) of keeping stuff fast and simple. The CSS rendering requires creating classes for every Latin character with their metrics encoded in CSS. That's not sustainable.

I am no KaTeX developer, but I have this vague feeling that it might just not be a good idea to be dabbling in these boundaries of visual accessibility.

**Comment by lesonli** [comment]
I have solved this problem.
In chrome, we can remove the 12px limit by setting the minimum font size.
This is the configuration address: chrome://settings/fonts
