### ISSUE TITLE
Documentation: empty list of previous versions 

### ISSUE THREAD

**Issue by deining** [KaTeX/KaTeX#2909]
**Documentation:**

https://katex.org/versions.html

```
Past Versions

Here you can find documentation for previous versions of KaTeX.
```

An empty list is presented here. This wasn't the case with version 0.13.0. With this version, links to documentation and release notes for several previous versions were presented. Looks like a regression to me.

**Comment by ylemkimon** [comment]
Thank you for reporting! This is an intended change, they will now show only recent versions. Documentation for `0.13.0` and `0.13.1` were not built due to an error, so I've rebuilt them and they should be shown now. You can find old versions at: https://6046e45eb2b96200078d0663--katex.netlify.app/versions.html.
