### ISSUE TITLE
renderAsDisplayMath

### ISSUE THREAD

**Issue by nschloe** [KaTeX/KaTeX#3050]
I would like to use KaTeX to render as display math all contents of
```
<pre lang="math">
a^2 + b^2 = c^2
</pre>
```
I tried
```js
for (let element of document.querySelectorAll("pre[lang='math']")) {
  renderMathInElement(element);
}
```
but `renderMathInElement` *searches* the text nodes for delimiters etc. Is there a function like `renderAsDisplayMath`? What would also work is `<pre lang="math">` as delimiter, but that fails too.

**Comment by nschloe** [comment]
Got it:
```js
      katex.render(element.textContent, element, {
          displayMode: true,
          throwOnError: false
      });
```
does the trick.

**Comment by edemaine** [comment]
You might also be interested in the [mathtex-script-type](https://github.com/KaTeX/KaTeX/tree/master/contrib/mathtex-script-type) extension, which converts the contents of `<script type="math/tex">` tags (instead of `<pre lang="math">` tags).  I believe the advantage of this is that you need less escaping (e.g. `<` and `>`) within `<script>` tags (but don't quote me on that).
