### ISSUE TITLE
Ability to use third-party LaTeX packages (\usepackage) 

### ISSUE THREAD

**Issue by rosikand** [KaTeX/KaTeX#3058]
Hello, 

I often use applications that make use of KaTeX (Notable, Notion). I find the KaTeX mathematical typesetting experience wonderful and much more efficient to work with than a standard LaTeX/TeX document editor. However, sometimes, when I use LaTeX, I want to use an external third-party package by importing it via `\usepackage{...}`. 

Does KaTeX plans to support third-party packages in the future? 

I am sorry in advance if this feature has already been discussed somewhere that I might have missed. 

Thank you!

**Comment by edemaine** [comment]
Unfortunately, this is impossible or at least a very long way away.  KaTeX is far from a full TeX parser, so packages written in TeX will not simply run in KaTeX. 
 Instead, they generally need to be rewritten into JavaScript.  KaTeX does have basic macro support, but it lacks a lot of features (listed in other issues here) that would be needed for importing a package.  Even if we added those features, many packages simply wouldn't work in a KaTeX environment because the web is just different from DVI or PDF output.

If you have a specific package you're interested in, feel free to request it in a new issue. KaTeX [supports many functions](https://katex.org/docs/supported.html) from [many different packages](https://github.com/KaTeX/KaTeX/wiki/Package-Emulation), and if a package is easy enough to support, it's possible to add it.
