### ISSUE TITLE
CDN during release

### ISSUE THREAD

**Issue by edemaine** [KaTeX/KaTeX#3209]
If you got to https://katex.org right now (if you're fast enough), you won't see any KaTeX rendering.  The CDN fails to load `katex@0.13.15`, presumably because jsdelivr hasn't updated yet.

It's probably not many minutes, but I wonder whether this could be fixed (in a stop-gap sense), e.g., by using `https://cdn.jsdelivr.net/npm/katex@latest` instead of `https://cdn.jsdelivr.net/npm/katex@0.13.15`?

**Comment by ylemkimon** [comment]
Actually, I manually stopped `v0.13.15` release to release other commits together but it was after the https://github.com/KaTeX/KaTeX/commit/a2a7c279cf63e628f21504b1b82991f420051032 was committed. `v0.13.16` is released but due to a Netlify bug, deploy wasn't started. I've restarted the deploy and it's deployed now. As you can see, the CDN is deployed almost instantly after a release, so normally there wouldn't be much a delay.

**Comment by edemaine** [comment]
Ah, I see.  This explains why the v0.13.15 changelog is missing, and why NPM lacks a v0.13.15.  Should we release that for historical interest?  We should add the changelog at least.

**Comment by ylemkimon** [comment]
I've added relevant changelogs and a note to the release note: https://github.com/KaTeX/KaTeX/releases/tag/v0.13.16.

**Comment by edemaine** [comment]
Oops, sorry for conflicting work.  Should I/you turn v0.13.15 back into a tag only, or remove the note from v0.13.16?

**Comment by ylemkimon** [comment]
Sorry for the hassle! I think we need better ways to hold off the release.

**Comment by edemaine** [comment]
@ylemkimon Maybe a special label on PRs of "skip release", added before merging?
