### ISSUE TITLE
Official TextMate grammar

### ISSUE THREAD

**Issue by fabiospampinato** [KaTeX/KaTeX#3218]
**Is your feature request related to a problem? Please describe.**

I embed KaTeX in a note-taking app, and as a next step in integration I'd like to provide some nice syntax-highlighting for it, however no TextMate grammar exists for it.

**Describe the solution you'd like:**

I'd be cool if an official TextMate grammar became available. TextMate grammars are basically what every editor uses for syntax highlighting stuff.

**Link to or name of a (La)TeX package that provides the same feature:**

N/A

**Describe alternatives you've considered:**

Writing my own? That's something I'm considering doing eventually in the future, however at the moment I don't have the resources to push for that.

**Additional context:**

There's [this](https://github.com/textmate/latex.tmbundle) grammar for TeX, which is also what GitHub is uses, however it doesn't seem very nice at all.

**Comment by edemaine** [comment]
Some questions:
1. I'm a little confused why this is KaTeX-specific, and not LaTeX-general. Could you clarify? Maybe because you want to capture math only? Probably would apply well to MathJax too?
2. Did you want a grammar for Markdown + LaTeX math, or some other combination? A grammar for LaTeX alone is probably not what you want.

I'm certainly all for syntax-highlighting grammars, though I worry about the complexity of X + LaTeX math for too many values of X.  Maybe Markdown is all that's important, though; I certainly agree that that would be useful.  For example, GitLab supports exactly that combination, though I believe with a weird math delimiter.

Probably worth checking that MathJax and/or GitLab haven't done anything. I found [some](https://stackoverflow.com/questions/33965829/syntax-highlighting-of-math-in-markdown-file) [StackOverflow](https://stackoverflow.com/questions/65920958/vs-code-latex-syntax-in-markdown) [questions](https://stackoverflow.com/questions/13611303/vim-maths-syntax-highlighting) and [answers](https://stackoverflow.com/questions/32865744/vim-syntax-and-latex-math-inside-markdown). Note that VSCode (since June 2021) supports Markdown + LaTeX syntax, in particular letting you hover over math and it shows a KaTeX rendering.  So there might be a grammar there already that you could port to your editor of choice.

**Comment by fabiospampinato** [comment]
> I'm a little confused why this is KaTeX-specific, and not LaTeX-general. Could you clarify? 

I'm embedding KaTeX specifically in my app, so that's what I want to syntax highlight. I don't believe KaTeX implements all of LaTeX yet, right? 🤔 Otherwise I could just use a LaTeX grammar for highlighting KaTeX, but I'm not sure there is a good one, I'm getting the following with the one GitHub is using (I believe):

<img width="564" alt="Screen Shot 2021-09-01 at 12 50 01" src="https://user-images.githubusercontent.com/1812093/131659024-f57fa0f1-829b-41dd-8da8-eadff9ce6de1.png">

And this with the dark theme:

<img width="684" alt="Screen Shot 2021-09-01 at 12 54 38" src="https://user-images.githubusercontent.com/1812093/131659605-c4238050-e374-4841-8b74-2c520384ba6a.png">

Now that I think about it I may need to update the TextMate theme though, that output with the dark theme doesn't look right at all.

> Maybe because you want to capture math only?

I want to syntax highlight KaTeX only yes.

> Probably would apply well to MathJax too?

Maybe, I don't know much about MathJax.

> Did you want a grammar for Markdown + LaTeX math, or some other combination? A grammar for LaTeX alone is probably not what you want.

I want a nice grammar for KaTeX alone. I'm embedding KaTeX in Markdown but I already have a grammar for Markdown.

> Probably worth checking that MathJax and/or GitLab haven't done anything. I found some StackOverflow questions and answers. Note that VSCode (since June 2021) supports Markdown + LaTeX syntax, in particular letting you hover over math and it shows a KaTeX rendering. So there might be a grammar there already that you could port to your editor of choice.

I should probably take a closer look at that, according to the gifs [here](https://github.com/James-Yu/LaTeX-Workshop) there might already be a nice LaTeX grammar (which may be good enough for highlighting KaTeX too although there might be some differences), maybe I just need to tweak my theme a little 🤔 I'll post an update once I'll figure this out 👍

**Comment by edemaine** [comment]
Thanks for clarifying!  I don't see why a syntax highlighting grammar would care about which features (commands) of LaTeX are implemented by KaTeX. The grammar should mainly care about lexing properly, and the lexical structure should be the same (or at least, any exceptions are bugs, and have been decreasing over time, so should be small). 

So any LaTeX grammar *ought* to work.  For example, the code you gave above syntax highlights correctly in GitHub:
```latex
\f{x} = \int_{-\infty}^\infty \f\hat\xi\,e^{2 \pi i \xi x} \,d\xi
```

**Comment by fabiospampinato** [comment]
> I don't see why a syntax highlighting grammar would care about which features (commands) of LaTeX are implemented by KaTeX.

For example, I got the following snippet of LaTeX from wikipedia:

```tex
\documentclass{article} % Starts an article
\usepackage{amsmath} % Imports amsmath
\title{\LaTeX} % Title

\begin{document} % Begins a document
  \maketitle
  \LaTeX{} is a document preparation system for
  the \TeX{} typesetting program. It offers
  programmable desktop publishing features and
  extensive facilities for automating most
  aspects of typesetting and desktop publishing,
  including numbering and  cross-referencing,
  tables and figures, page layout,
  bibliographies, and much more. \LaTeX{} was
  originally written in 1984 by Leslie Lamport
  and has become the  dominant method for using
  \TeX; few people write in plain \TeX{} anymore.
  The current version is \LaTeXe.

  % This is a comment, not shown in final output.
  % The following shows typesetting  power of LaTeX:
  \begin{align}
    E_0 &= mc^2 \\
    E &= \frac{mc^2}{\sqrt{1-\frac{v^2}{c^2}}}
  \end{align} 
\end{document}
```

Highlighting it with a LaTeX grammar gives me something that looks like this:

<img width="405" alt="Screen Shot 2021-09-03 at 18 59 38" src="https://user-images.githubusercontent.com/1812093/132041896-1518bba3-bd11-4f83-b595-096c3cd55e5f.png">

As you can see the `\documentclass` command is being recognized, it's not just any command that gets highlighted red, however when passing that to KaTeX I'm getting the following error:

```
ParseError: KaTeX parse error: Undefined control sequence: \documentclass at position 1: \̲d̲o̲c̲u̲m̲e̲n̲t̲c̲l̲a̲s̲s̲{article} % Sta…
    at new t (webpack:///./node_modules/katex/dist/katex.min.js?:1:1923)
    at t.e.parseGroup (webpack:///./node_modules/katex/dist/katex.min.js?:1:253484)
    at t.e.parseAtom (webpack:///./node_modules/katex/dist/katex.min.js?:1:248190)
    at t.e.parseExpression (webpack:///./node_modules/katex/dist/katex.min.js?:1:247079)
    at t.e.parse (webpack:///./node_modules/katex/dist/katex.min.js?:1:246749)
    at Ma (webpack:///./node_modules/katex/dist/katex.min.js?:1:256147)
    at Ta (webpack:///./node_modules/katex/dist/katex.min.js?:1:256943)
    at Object.renderToString (webpack:///./node_modules/katex/dist/katex.min.js?:1:257063)
    at Object.render (webpack:///./src/apps/core/plugins/markdown/lib/katex.ts?:42:71)
    at async replace (webpack:///./src/apps/core/plugins/markdown/default.ts?:475:35)
    at async Compiler._execTransform (webpack:///./src/apps/core/lib/markdown/compiler.ts?:415:41)
    at async renderer (webpack:///./src/apps/core/lib/markdown/compiler.ts?:163:31)
```

The, somewhat minor, issue with highlighting KaTeX with grammars for LaTeX is that the syntax highlighting basically tells me that that's valid LaTeX, and KaTeX tells me that that's not valid KaTeX. Since KaTeX and LaTeX don't overlap 100% there's this dissonance of the syntax highlighting recognizing stuff that the language itself (KaTeX) doesn't actually support.

A perfect grammar for KaTeX wouldn't have this issue, but a perfect grammar for KaTeX doesn't exist, hence this issue.

I think it's a fairly minor issue, and it probably makes more sense to close the gap with LaTeX in features rather than spend time on making a proper grammar, still it's an issue nonetheless.

**Comment by edemaine** [comment]
> syntax highlighting basically tells me that that's valid LaTeX

In my opinion, you're asking too much from your syntax highlighter.  I would say that an ideal syntax highlighter detects **lexically correct** code, but not actual validity of the input.  For example, `\foobar{x}` is lexically correct, but not valid in LaTeX or KaTeX (both will throw an "Undefined command/control sequence" error). Because LaTeX and KaTeX allow defining commands at run time, it is provably impossible to know which commands are defined when parsing, except by running the code itself.  I believe the general view by syntax highlighters is that they should *not* do this, but should just be running the lexing process and highlighting the different types of tokens.  That lexing process is pretty similar between LaTeX and KaTeX.  (In fact, I would expect that most LaTeX syntax highlighters follow a process much closer to KaTeX's, whereas in LaTeX you can't really even lex correctly without running the code itself, as every token can be redefined at runtime.)

Thanks for giving the specific example of what you don't like, though; that's more helpful. The special casing of `\documentclass` and `\usepackage` is just special casing; it's not like the syntax highlighter knows what those commands mean, only that they're worth coloring red. (I would venture to guess that it doesn't even know how many arguments they take, only their names.)  I could see some value to adding a set of "red commands" that matches exactly what's in [KaTeX's support table](https://katex.org/docs/support_table.html) (but commands not on that list should definitely also be allowed). This should be a very small tweak to any existing LaTeX syntax highlighter (just updating one list of commands to another). Perhaps you'd be willing to try doing so yourself?

**Comment by fabiospampinato** [comment]
I don't think textmate grammars are expected to check the validity of code, I mean as you point out in LaTeX and other languages that requires executing the code, and even then whether some code is valid or not may depend on the environment it is being run in, so I totally don't expect grammars to do that too.

I'm just saying the LaTeX grammar is tokenizing `\documentclass` specially because it recognizes it as a valid LaTeX command, if the same person that wrote the grammar for LaTeX instead wrote the grammar for KaTeX he/she wouldn't tokenize `\documentclass` the same way because it would be nonsensical, hence the LaTeX grammar doesn't look like the hypothetical perfect KaTeX grammar.

That being said I agree that's a really minor issue, if there are other issues like that I don't really know since I barely know any LaTeX/KaTeX at all to being with.

> Perhaps you'd be willing to try doing so yourself?

I'll see what I can do, resources are limited at the moment though and already I must have some bugs somewhere because the LaTeX grammar isn't working properly for me.

I'm closing the issue since there doesn't seem anything in the near future to do here for the maintainers, I'll post an update if I can find or make a slightly better grammar 👍.

**Comment by edemaine** [comment]
Sounds good. Keep us posted!
