### ISSUE TITLE
Wrong position of \in in subscript

### ISSUE THREAD

**Issue by GoBigorGoHome** [KaTeX/KaTeX#3219]
![image](https://user-images.githubusercontent.com/9896288/131607071-2a94f62f-b968-486f-8a16-cf8ac2521725.png)

**Comment by edemaine** [comment]
@GoBigorGoHome Thanks for spotting this.  It seems to affect all binary operators (e.g. `\subset` too).

@ylemkimon I bisected and this bug turns out to be caused by #2866. (It works before the merge, doesn't work immediately after.) Any ideas what's going wrong? I tried inspecting in https://opentype.js.org/glyph-inspector.html but I don't see any difference between the glyphs...

**Comment by edemaine** [comment]
Update: the difference between the font files seems to be that bit 3 of `flags` is set, which enables [font hinting](https://en.wikipedia.org/wiki/Font_hinting). (Specifically, `flags` is 15 in the new fonts, but 11 in the old fonts.)

Confusingly, we've always been using `ttfautohint`, but the PR did upgrade `ttfautohint` from 1.3 to 1.8.3-2build1...
