### ISSUE TITLE
add support for missing \nsubset and \nsupset symbols

### ISSUE THREAD

**Issue by joseluis** [KaTeX/KaTeX#3246]
There's already support for:

|symbol|code|
|:-:|-|
⊈ | \nsubseteq 
 || \nsubseteqq
⊉|\nsupseteq
||\nsupseteqq
 
but funnily enough there's no support yet for the more common:

symbol | code
|:-:|-|
⊄ | \nsubset
⊅ | \nsupset

**Comment by edemaine** [comment]
KaTeX doesn't have them probably because they're not in amsmath or base LaTeX (unlike the eq variations).

Meanwhile, you can use `\not\subset` and `\not\supset`, or define macros yourself, e.g., `\gdef\nsubset{\not\subset}`. They don't look beautiful, but certainly clear.

I do see some symbols for `\nsubset` and `\nsupset` in the [comprehensive symbols list](http://tug.ctan.org/info/symbols/comprehensive/symbols-a4.pdf), so I could see adding something to KaTeX.   Macros would be the easiest; adding to the fonts would require choosing a maximally compatible symbol...

**Comment by joseluis** [comment]
> `\not\subset`

That's fantastic, thank you. I didn't realize I could do that. This solves it for me.
