### ISSUE TITLE
\circ vs ∘ spacing

### ISSUE THREAD

**Issue by Drekin** [KaTeX/KaTeX#3578]
The function composition denoted by $f \circ g$ produces correct spacing of a binary operator, while writing directly $f ∘ g$ does not 
(see [the demo](https://katex.org/?data=%7B%22displayMode%22%3Atrue%2C%22leqno%22%3Afalse%2C%22fleqn%22%3Afalse%2C%22throwOnError%22%3Atrue%2C%22errorColor%22%3A%22%23cc0000%22%2C%22strict%22%3A%22warn%22%2C%22output%22%3A%22htmlAndMathml%22%2C%22trust%22%3Afalse%2C%22macros%22%3A%7B%22%5C%5Cf%22%3A%22%231f(%232)%22%7D%2C%22code%22%3A%22f%20%5C%5Ccirc%20g%20%5C%5C%5C%5C%5Cnf%20%E2%88%98%20g%20%5C%5C%5C%5C%5Cnf%20%5C%5Ccdot%20g%20%5C%5C%5C%5C%5Cnf%20%E2%8B%85%20g%22%7D)) even though \circ and the U+2218 should be synonyms (https://github.com/KaTeX/KaTeX/blob/8cf6b52df29f96c04645ed32e9268102b2cd5b6a/src/symbols.js#L541). For $f \cdot g$ and $f ⋅ g$ the behavior is correct.

**Comment by Drekin** [comment]
It seems that the same problem is with some other binary operators, e.g. \bullet and \setminus.

**Comment by ronkok** [comment]
Good catch. I'll work up a PR that gives operator spacing to Unicode character U+2218, the analog to `\circ`.

Regarding `\bullet` and `\setminus`, we avoided them because there is more than one Unicode code point that could map to either control word. and at that time we were avoiding ambiguities in general. I also think that the current KaTeX fonts have chosen the wrong Unicode code point for each of them. So a solution would need remapping of those two code points in the KaTeX font. It's the sort of thing that deserves its own PR.

@edemaine If you are willing to do the font remapping work, I could begin that second PR with a revision to `symbols.js`. Any interest?

**Comment by edemaine** [comment]
Happy to take a look (though it may not be for a couple of weeks). What are the "correct" codepoints for those characters that you'd like to move them to?

**Comment by ronkok** [comment]
I withdraw my comment regarding the code point for `\setminus`. It's fine.

The situation for `\bullet` is ambiguous. KaTeX currently has it at code point U+2219, Bullet Operator. That's good semantically. However, a couple of math fonts (Cambria Math and Asana) have a small dot at that code point, more like `\cdot`.  It was silly of them to do that because `\cdot` already has a Unicode code point at U+22c5. But there it is and if someone copies and pastes from KaTeX ouput into another document, they are likely to see that little dot.

So for `\bullet`, I considered using U+2022, Bullet. All the math fonts use a similarly sized dot for that glyph. 

There's the ambiguity. The current KaTeX `\bullet` code point is better semantically, but visually a change would be better for a few use cases. In the end, it's probably not worth the trouble to recode the font.

**Comment by Drekin** [comment]
Thank you for a quick fix!
