### ISSUE TITLE
CSS line break doesn't work in split equations?

### ISSUE THREAD

**Issue by mazayadigital** [KaTeX/KaTeX#3628]
Hi everyone,

I have this split equation:
```latex
$$\begin{split} err &= \left(\int_{-\infty}^\infty (p(x) - f(x))^2 dx\right)^{0.5}\\&=\left(\textstyle\sum_{i=0}^{2^n-1} \displaystyle\int_{x \isin D_i} (p_i - f(x))^2dx + \int_{x\notin D} f(x)^2dx\right)^{0.5}\end{split}$$
```

It renders fine, but when applying the CSS for linebreak, the equation doesn't wrap. Is it to do with split?
.katex-display > .katex { white-space: normal } 

![Screenshot 2022-05-06 011841](https://user-images.githubusercontent.com/96816041/167046961-4db97873-b19d-411f-b35f-8635cc036d6e.jpg)

**Comment by ronkok** [comment]
@mazayadigital I think the problem is just that the line separator should be `\\`, not `\`. See the [rendered math](https://katex.org/?data=%7B%22displayMode%22%3Atrue%2C%22leqno%22%3Afalse%2C%22fleqn%22%3Afalse%2C%22throwOnError%22%3Atrue%2C%22errorColor%22%3A%22%23cc0000%22%2C%22strict%22%3A%22warn%22%2C%22output%22%3A%22htmlAndMathml%22%2C%22trust%22%3Afalse%2C%22macros%22%3A%7B%22%5C%5Cf%22%3A%22%231f(%232)%22%7D%2C%22code%22%3A%22%5C%5Cbegin%7Bsplit%7D%20err%20%26%3D%20%5C%5Cleft(%5C%5Cint_%7B-%5C%5Cinfty%7D%5E%5C%5Cinfty%20(p(x)%20-%20f(x))%5E2%20dx%5C%5Cright)%5E%7B0.5%7D%5C%5C%5C%5C%26%3D%5C%5Cleft(%5C%5Ctextstyle%5C%5Csum_%7Bi%3D0%7D%5E%7B2%5En-1%7D%20%5C%5Cdisplaystyle%5C%5Cint_%7Bx%20%5C%5Cisin%20D_i%7D%20(p_i%20-%20f(x))%5E2dx%20%2B%20%5C%5Cint_%7Bx%5C%5Cnotin%20D%7D%20f(x)%5E2dx%5C%5Cright)%5E%7B0.5%7D%5C%5Cend%7Bsplit%7D%22%7D).

**Comment by edemaine** [comment]
Line breaks only happen automatically at the top level. You won't get line breaks inside `\left(...\right)`. But I suspect you also won't get line breaks inside `\begin{split}...\end{split}`, because it's essentially a `tabular` environment, and there's no way to do automatic line breaks in tables. (In LaTeX or KaTeX.) 🙁

**Comment by mbourne** [comment]
I had a look at this as an exercise.

mazayadigital's equation can wrap, and looks as follows:

![Capture](https://user-images.githubusercontent.com/7541940/167557304-f6a6c47b-cb90-4623-b99d-a29b667fda97.PNG)

The trickery is due to splitting the expression at the "+" sign and doing a post-processing step that aligns the wrapped portion of the equation in an appropriate place. I'm also using ASCIIMath input, but I think the same effect would be possible with LaTeX input.

I put this and some other wrapping ideas on this demo page:

https://bourne2learn.com/math/katex/katex-wrap-examples.php

(View it on a phone.)

I know this doesn't fit with KaTeX's philosophy of LaTeX purity, but it works for me since it's readable on both phone and desktop.

Regards
Murray
