### ISSUE TITLE
Italic partial or upright partial?

### ISSUE THREAD

**Issue by Firestar-Reimu** [KaTeX/KaTeX#3658]
![image](https://user-images.githubusercontent.com/65082432/173309199-2dc950e8-33a7-4d6c-b1b6-bc4ffb4cf90f.png)

I found that katex display mathjax-like italic partial sign here.

But I remember there is a ugly, shortened upright version of katex partial. ~~(I searched it for an hour but failed)~~

OK, maybe like this: (https://katex.org/docs/supported.html)

the documentation says that direct input will render as upright partial

![Screenshot_20220615_012241](https://user-images.githubusercontent.com/65082432/173638857-6512359d-a4a9-4ca3-ab22-64a3803aff50.png)

And this is the main reason I do not use katex.

How to force katex to display italic partial sign?

**Comment by edemaine** [comment]
`\frac{∂y}{∂x}` already produces italic partials:

![image](https://user-images.githubusercontent.com/2218736/173640246-99cd694c-49b3-442d-b03f-8495f0937b58.png)

With my fonts, the documentation also looks italic:

![image](https://user-images.githubusercontent.com/2218736/173640370-81ceb6c4-5fab-4578-b0de-aa81d3d37234.png)

We're actually just displaying Unicode characters there so that you can copy/paste to test them out. But before claiming there's a bug in KaTeX, you might actually try it out by pasting into the demo app...

**Comment by Firestar-Reimu** [comment]
I think ∂∇ℑℲℵℶℷℸ⅁ℏð differs because I installed Latex Modern math, depending on my installed fonts. Thanks!

**Comment by edemaine** [comment]
KaTeX uses its own fonts and should render the same on all devices. The only confusion was that line of the *documentation*, which doesn't use KaTeX fonts.
