### ISSUE TITLE
Hash (#) causes unexpected parse error

### ISSUE THREAD

**Issue by dobesv** [KaTeX/KaTeX#3728]
**Describe the bug:**

An unescaped `#` character causes a parse error in KaTeX.  This makes some sense but it would be nice to render on a best-effort basis if possible.

**(La)TeX code:**

The code of (La)TeX you tried to render:

```latex
bag\enspace a:\enspace mass\enspace(g)\enspace9.529\enspace\frac{#}{ml}\enspace volume\enspace(ml)+\enspace10.06\enspace(g)
```

**Expected behavior:**

It seems possible that when `#` is used without a number after, or used with a number but outside a custom command body, it could be output as if it were escaped.

QuickLaTeX does accept this input, although it does not render the `#` character:

![image](https://user-images.githubusercontent.com/327833/192622632-8453561c-c74e-4677-96f6-e77a6bbab429.png)

We ran into this because the [MathLive keyboard inserts `#` unescaped](https://github.com/arnog/mathlive/issues/1642) if the user types it in, so our users are occasionally running into rendering errors.

**Comment by edemaine** [comment]
This is expected behavior, given that it's how LaTeX behaves. You're supposed to use `\#` to enter a hash character. It seems like MathLive should do this when converting input to LaTeX?

QuickLaTeX doesn't show LaTeX errors by default.  But if you check the "Report LaTeX errors" box, you'll see that it's actually crashing:
```
You can't use `macro parameter character #' in math mode.
```

Admittedly, (La)TeX has nicer support for errors in that it will try to struggle through with the input even when there's a parse error like this. That'd be interesting to add to KaTeX, but it's a pretty major undertaking. It looks like this is the ancient issue #428.

**Comment by dobesv** [comment]
Hmm yeah I investigated a bit and other LaTeX renderers also fail on this input.  I'll close in favor of #428.
