### ISSUE TITLE
\hfill not supported

### ISSUE THREAD

**Issue by ShaySheng** [KaTeX/KaTeX#3748]
\hfill is very important in equation alignment

My equation was like this in markdown: 

```
$$\begin{matrix}
\omega(t)&=&\frac{\phi_s(f(\textbf{p}(t)))}{\int_{-\infty}^{+\infty}\phi_s(f(\textbf{p}(u)))du} \hfill\\
&=& \frac{\phi_s(f(\textbf{p}(t)))}{\int_{-\infty}^{+\infty}\phi_s( -|\cos(\theta)|\cdot (u-t^*) )du} \\ 
&=& \frac{\phi_s(f(\textbf{p}(t)))}{|\cos(\theta)|^{-1}\int_{-\infty}^{+\infty}\phi_s((u-t^*) )du}  
\end{matrix}$$
```

<img width="343" alt="截屏2022-11-05 21 15 17" src="https://user-images.githubusercontent.com/57656091/200121742-5b27408e-5e2e-4e95-90ec-54ecc0d7d220.png">

If I want to align the equation to the left, I'd add \hfill to the right of the line, left of line break`\\`

But when I add it to my latex equation, I got this:

"ParseError: KaTeX parse error: Undefined control sequence: \hfill at position xxx"

I want KaTex to add this control sequence \hifll , or **what else ways do you have to align the equations to the left**😂

Could you tell me?

I use "Markdown Preview Enhanced v0.6.5" in vscode to preview my markdown

**Comment by pedrolimasi** [comment]
Maybe you should try the `aligned` environment instead of `matrix`.

```latex
\begin{aligned}
\omega(t)
&=
\frac{\phi_s(f(\textbf{p}(t)))}{\int_{-\infty}^{+\infty}\phi_s(f(\textbf{p}(u)))du} \hfill\\
&=
\frac{\phi_s(f(\textbf{p}(t)))}{\int_{-\infty}^{+\infty}\phi_s( -|\cos(\theta)|\cdot (u-t^*) )du} \\ 
&=
\frac{\phi_s(f(\textbf{p}(t)))}{|\cos(\theta)|^{-1}\int_{-\infty}^{+\infty}\phi_s((u-t^*) )du}  
\end{aligned}
```

$$
\begin{aligned}
\omega(t)
&=
\frac{\phi_s(f(\textbf{p}(t)))}{\int_{-\infty}^{+\infty}\phi_s(f(\textbf{p}(u)))du} \hfill\\
&=
\frac{\phi_s(f(\textbf{p}(t)))}{\int_{-\infty}^{+\infty}\phi_s( -|\cos(\theta)|\cdot (u-t^*) )du} \\ 
&=
\frac{\phi_s(f(\textbf{p}(t)))}{|\cos(\theta)|^{-1}\int_{-\infty}^{+\infty}\phi_s((u-t^*) )du}  
\end{aligned}
$$

**Comment by ShaySheng** [comment]
<img width="1201" alt="ScreenShot2022-11-11 20 47 56" src="https://user-images.githubusercontent.com/57656091/201344442-bdf7c9ae-effa-47fb-89c8-56dd9d73c033.png">
It still doesn't work in Katex environment with `\hfill`
<img width="1117" alt="ScreenShot2022-11-11 20 48 16" src="https://user-images.githubusercontent.com/57656091/201344456-4b76acb7-5668-4e55-8db8-fdfbb8a2c155.png">

**Comment by edemaine** [comment]
This issue is already tracked in #990, but thanks for adding some examples of where you'd like to use it!

Unfortunately, the way `array` environments are implemented right now (including `align` and `aligned`), it would be difficult to implement `\hfill`, I believe.

> what else ways do you have to align the equations to the left

You can use the `fleqn: true` [option](https://katex.org/docs/options.html).

**Comment by ShaySheng** [comment]
@edemaine Thank you very much😂
