### ISSUE TITLE
Coloring only the brackets around an expression

### ISSUE THREAD

**Issue by gxyd** [KaTeX/KaTeX#3808]
See the below code:

**(La)TeX code:**
The code of (La)TeX you tried to render:
```latex
\textcolor{red}{\left(}x\textcolor{red}{\right)}
```

**Expected behavior:**

I expected the output to look like: $\textcolor{red}{(}x\textcolor{red}{)}$

**What works:**

When I try to render the code: `\textcolor{red}{(}x\textcolor{red}{)}` (i.e. replacing `\left(` with `(` and `\right)` with `)`. The code renders just fine.

**Comment by edemaine** [comment]
This is how LaTeX works. `\left` and `\right` need to be balanced (they can't be inside separate braced scopes) so that it knows what to measure.

You have two alternatives:

1. Use `\color`, e.g., `\color{red}\left(\color{black}x\color{red}\right)`
2. Use manually sized brackets, like `\big`, `\bigg`, etc.  E.g. `\textcolor{red}{\big(}x\textcolor{red}{\big)}`
