### ISSUE TITLE
`\!'`: KaTeX parse error: Got group of unknown type: 'internal'

### ISSUE THREAD

**Issue by nschloe** [KaTeX/KaTeX#3900]
Trying to move a prime symbol `'` slightly to the left, e.g., to emulate arc seconds,
```
.\!''
```
gives the KaTeX error
```
KaTeX parse error: Got group of unknown type: 'internal'
```

**Comment by edemaine** [comment]
Thanks for all your reports! However, I'm not sure you need to document every single context where super and subscripts currently can't be placed. In particular, this one seems redundant with #3878. It would be much more helpful to merge all of these examples into a single issue, as the root cause is identical.

**Comment by nschloe** [comment]
Didn't realize this is a duplicate, the MWE doesn't involve super- or subscripts. Since the error message is the same, the issues probably share some code paths though. Will add this #3878.
