### ISSUE TITLE
Bad rendering in formulas with fractions

### ISSUE THREAD

**Issue by Pablo200206** [KaTeX/KaTeX#3952]
**Describe the bug:**
bad formula rendering, the fractions renders collapsed

**(La)TeX code:**
The code of (La)TeX you tried to render:
```latex
%ΔP=Pnuevo−PviejoPviejo×100% \Delta P = \frac{P_{nuevo} - P_{viejo}}{P_{viejo}} \times 100
```

**Expected behavior:**
A clear and concise description of what you expected to happen. KaTeX's general goal is to render as LaTeX does, so if possible, please include a LaTeX rendering. You can obtain one using [QuickLaTeX](https://www.quicklatex.com/).

**Screenshots:**
![image](https://github.com/KaTeX/KaTeX/assets/108026713/f6c48491-f670-4be6-91f3-dcdc4261081d)
**Environment (please complete the following information):**
 - KaTeX Version: 0.16.10
 - Device: Desktop
 - OS: Windows
 - Browser: Chrome, Edge
 - Version: Edge 125.0.2535.51

**Comment by edemaine** [comment]
We'd need more information to help with this, as it's probably specific to your environment. Did you try it on the katex.org demo site? It [seems to work fine](https://katex.org/?data=%7B%22displayMode%22%3Atrue%2C%22leqno%22%3Afalse%2C%22fleqn%22%3Afalse%2C%22throwOnError%22%3Atrue%2C%22errorColor%22%3A%22%23cc0000%22%2C%22strict%22%3A%22warn%22%2C%22output%22%3A%22htmlAndMathml%22%2C%22trust%22%3Afalse%2C%22macros%22%3A%7B%22%5C%5Cf%22%3A%22%231f(%232)%22%7D%2C%22code%22%3A%22%5C%5C%25%CE%94P%3DPnuevo%E2%88%92PviejoPviejo%C3%97100%5C%5C%25%20%5C%5CDelta%20P%20%3D%20%5C%5Cfrac%7BP_%7Bnuevo%7D%20-%20P_%7Bviejo%7D%7D%7BP_%7Bviejo%7D%7D%20%5C%5Ctimes%20100%22%7D), though I added some `\`s to escape the `%` signs (otherwise they are treated as comments).

![image](https://github.com/KaTeX/KaTeX/assets/2218736/626f1bff-e93d-442e-8533-f5278e5dbeb7)

**Comment by Pablo200206** [comment]
ChatGPT
Hello, I'm using Angular 16 and this happens to me with all fraction formulas. I have commented out all the CSS code in case there was some type of overriding that was affecting KaTeX, but that wasn't the problem.

I'm capturing the formulas from a data stream from the backend (it's an AI chatbot) and passing them via the renderToString function in the innerHTML

**Comment by edemaine** [comment]
Can you share the full HTML and CSS for a page (or URL or repo) that has the issue?  Probably it's a stray CSS rule that's conflicting with KaTeX. (I'd guess one of the many `.vlist` elements.)
