### ISSUE TITLE
\text{⋮} causes error message

### ISSUE THREAD

**Issue by pzinn** [KaTeX/KaTeX#3990]
\text{⋮} will cause an error message:
KaTeX parse error: Can't use function '\mathord' in text mode at position 1: \̲m̲a̲t̲h̲o̲r̲d̲{\varvdots\rule…
other ellipsis unicode characters seem to work fine.

**Comment by pzinn** [comment]
I'm happy to implement this.
Before I do so I want to make sure I understand the logic behind `\vdots` vs `\varvdots`. What's the difference between the two, and why should `⋮` be one rather than the other?

**Comment by ronkok** [comment]
Issue #620 pointed out that the `\vdots` in LaTeX 2ε is not just a symbol but also has a vertical kern.  So the [KaTeX code for `\vdots`](https://github.com/KaTeX/KaTeX/blob/main/src/macros.js#L337-L345) calls a macro. It calls a character from `symbols.js` that is named `\vardots` (a KaTeX-only name) and also includes an adjacent zero-width vertical rule to emulate the vertical kern.

The proposed code revises the macro. In text mode, the macro will just call the symbol, and in math mode, the macro will expand as it does currently.

@edemaine is better at macros than I am and he may come up with something more clever in review. But I think this does the job.

**Comment by ronkok** [comment]
> why should ⋮ be one rather than the other?

Mapping Unicode characters to LaTeX functions was an exercise that turned out to be harder than expected. The KaTeX mapping usually, but not always, follows [unicode-math](https://github.com/latex3/unicode-math/blob/master/unicode-math-table.tex).  KaTeX maps rhe character `⋮`, U+22EE, to `\vdots` as in in unicode-math, but we ignore their `\mathrel` provision because LaTeX 2ε does not give relation spacing to `\vdots`.
