### ISSUE TITLE
Treat non-breakable spaces as simple spaces.

### ISSUE THREAD

**Issue by arnaudpeich** [KaTeX/KaTeX#518]
Non-breakable spaces (`&nbsp;`) prevent formulas from rendering. It would be great if they could be detected and replaced with normal spaces before rendering.

A scenario where this would be useful is when you enter your equations in a rich-text editor and your equation contains multiple spaces (_e.g._ because you pasted from a text editor where you used spaces for alignment purposes).
The first space will remain normal but the subsequent spaces will be converted to `&nbsp;` by the editor.

**Comment by kevinbarabash** [comment]
@arnaudriegert I could see how that could be annoying.  Check if your editor has an command to paste unformatted text.

**Comment by arnaudriegert** [comment]
@kevinbarabash Yes I am also working on a fix on my side, but that would only apply to this specific scenario. I thought a KaTeX-side pre-cleaning would be appropriate too.

**Comment by gagern** [comment]
I'd say a simple `str.replace(/\u00a0/g, ' ')` on the whole input string should be all that is needed here for the purpose you describe. Personally I think this should be done in site-specific code, since it's part of the process of turning an author's input into TeX snippets and other things, as opposed to KaTeX' job of turning these TeX snippets into DOM for formulas. I also believe that there *might* be situations where this is not appropriate. Suppose KaTeX one day learns how to do `\parbox`. Then people might actually want to treat the Unicode non-breaking space as a synonym to the `~` TeX non-breaking space.

**Comment by kevinbarabash** [comment]
It might be worth having some snippets in `contrib` or in `README.md` with common transforms you might want to do.  I add a transform on the KA site code which converts `\begin{align*}` to `\begin{aligned}`.  I should add `str.replace(/\u00a0/g, ' ')` too because we're seeing this issue in existing content.
