### ISSUE TITLE
Latex Table support

### ISSUE THREAD

**Issue by mdhuilee** [KaTeX/KaTeX#550]
Katex is great! 

is it possible to provide latex table support? or is there a way to make /begin{table} ...

Thanks!

**Comment by gagern** [comment]
You can have `\begin{array}…` which may help in some situations.

**Comment by davwheat** [comment]
Yes, please!

**Comment by hakkurishian** [comment]
Is there any update on this one? I think this would be a great advancement to bring in some layouting capabilities

**Comment by edemaine** [comment]
I don't KaTeX can support `\begin{table}`; I'm not even sure what it would mean in an HTML environment, where LaTeX-style floats don't make a lot of sense.  However, you might instead be looking for:

* `tabular` environment (#2111). This is actually doable now that we support other top-level environments (thanks to @ronkok); it would act like an `array` where cells start in text mode instead of math mode. But it hasn't been implemented yet.
* More complete support for array environment (#269).

If you have specific requests or missing features, feel free to add them there. I am going to close this issue as I think those listed above are more relevant.
