### ISSUE TITLE
Support for non-standard macros \class and \cssId

### ISSUE THREAD

**Issue by hastebrot** [KaTeX/KaTeX#90]
Hi!

Support for the [TeX HTML extension from MathJax](http://docs.mathjax.org/en/latest/tex.html#html) in the output of KaTeX would be nice.

---

Excerpt from the docs:

The HTML extension gives you access to some HTML features like styles, classes, element ID’s and clickable links. It defines the following non-standard macros: 
- `\class{name}{math}`: Attaches the CSS class name to the output associated with math when it is included in the HTML page. This allows your CSS to style the element.
- `\cssId{id}{math}`: Attaches an id attribute with value id to the output associated with math when it is included in the HTML page. This allows your CSS to style the element, or your javascript to locate it on the page.

**Comment by rrandallcainc** [comment]
@kevinbarabash How do we feel about bringing this back from the dead? 

I know there's a few people who are looking for it.

If you're okay with the concept, I can see what I can about the implementation.

**Comment by kevinbarabash** [comment]
@rrandallcainc since this is non-standard it should probably go in contrib/.  In order to do that though, we need a way to add functions from outside of KaTeX core.  You could expose `defineFunction` as `__defineFunction`.  There should also be automated tests for this so that we can catch any changes to `defineFunction` that break these commands in contrib/.

**Comment by ylemkimon** [comment]
@kevinbarabash With strict mode in work, I think we can revisit this and consider enabling them in non-strict mode instead of `contrib`.
